---
- name: Solr
  hosts: all
  become: true
  vars:
    solr_version: "3.6.2"
    solr_workspace: /var/cache/solr
  pre_tasks:
    - name: create {{ solr_workspace }}
      file: path={{ solr_workspace }} state=directory
  roles:
    - geerlingguy.java
    - geerlingguy.solr
